var dynamicMarkets = [{'Market':'AEX','ShortName':'AEX'},
	{'Market':'FGBM','ShortName':'Bobl'},
	{'Market':'LCOE','ShortName':'Brent Oil'},
	{'Market':'FGBL','ShortName':'Bund'},
	{'Market':'CAC40','ShortName':'CAC 40'},
	{'Market':'CORN','ShortName':'Corn'},
	{'Market':'FDAX','ShortName':'DAX'},
	{'Market':'DJ5','ShortName':'Dow Jones'},
	{'Market':'EURJPY','ShortName':'EUR/JPY'},
	{'Market':'EUROUSD','ShortName':'EUR/USD'},
	{'Market':'FESX','ShortName':'EuroStoxx 50'},
	{'Market':'FSMI','ShortName':'FSMI'},
	{'Market':'FTSE','ShortName':'FTSE 100'},
	{'Market':'GASOIL','ShortName':'Gasoil'},
	{'Market':'RBOB','ShortName':'Gasoline (RBOB)'},
	{'Market':'GBPUSD','ShortName':'GBP/USD'},
	{'Market':'GOLD','ShortName':'Gold'},
	{'Market':'HS','ShortName':'Hang Seng'},
	{'Market':'JB','ShortName':'JPN-Bond 10Y'},
	{'Market':'KS','ShortName':'KOSPI 200'},
	{'Market':'LG','ShortName':'Long Gilt'},
	{'Market':'TW','ShortName':'MSCI Taiwan'},
	{'Market':'FNASDAQ','ShortName':'Nasdaq'},
	{'Market':'NGAS','ShortName':'Natural Gas'},
	{'Market':'NIKOS','ShortName':'Nikkei 225 OSE'},
	{'Market':'RS2000','ShortName':'RS2000'},
	{'Market':'SP500','ShortName':'S&P 500'},
	{'Market':'CAD60','ShortName':'S&P Canada 60'},
	{'Market':'SP400','ShortName':'S&P Midcap'},
	{'Market':'SOY','ShortName':'Soy'},
	{'Market':'SPI','ShortName':'SPI'},
	{'Market':'TN30','ShortName':'T-Bond 30'},
	{'Market':'TN10','ShortName':'T-Note 10'},
	{'Market':'TN5','ShortName':'T-Note 5'},
	{'Market':'TOPIX','ShortName':'Topix'},
	{'Market':'USDCHF','ShortName':'USD/CHF'},
	{'Market':'USDJPY','ShortName':'USD/JPY'},
	{'Market':'WHEAT','ShortName':'Wheat'},
	{'Market':'WTI','ShortName':'WTI Oil'},
	{'Market':'','ShortName':''}];
var klassikMarkets = [{'Market':'3ED','ShortName':'3M Eurodollar'},
	{'Market':'3ST','ShortName':'3M Sterling'},
	{'Market':'AEX','ShortName':'AEX'},
	{'Market':'ALU','ShortName':'Aluminum'},
	{'Market':'FAUDUSD','ShortName':'AUD/USD (CME)'},
	{'Market':'AU3M','ShortName':'AUS-Bill 3M'},
	{'Market':'AU10Y','ShortName':'AUS-Bond 10Y'},
	{'Market':'AU3Y','ShortName':'AUS-Bond 3Y'},
	{'Market':'FGBM','ShortName':'Bobl'},
	{'Market':'LCOE','ShortName':'Brent Oil'},
	{'Market':'FGBL','ShortName':'Bund'},
	{'Market':'CAC40','ShortName':'CAC 40'},
	{'Market':'BAX','ShortName':'CAN-Bill 3M'},
	{'Market':'CGB','ShortName':'CAN-Bond 10Y'},
	{'Market':'FCHFUSD','ShortName':'CHF/USD (CME)'},
	{'Market':'NIFTY','ShortName':'CNX Nifty'},
	{'Market':'COCOA','ShortName':'Cocoa'},
	{'Market':'COFFEE','ShortName':'Coffee'},
	{'Market':'COPPER','ShortName':'Copper'},
	{'Market':'CORN','ShortName':'Corn'},
	{'Market':'COTTON','ShortName':'Cotton'},
	{'Market':'FDAX','ShortName':'DAX'},
	{'Market':'FDX','ShortName':'Dollar Index'},
	{'Market':'DJ5','ShortName':'Dow Jones'},
	{'Market':'FEURUSD','ShortName':'EUR/USD (CME)'},
	{'Market':'EURIBOR','ShortName':'Euribor'},
	{'Market':'FESX','ShortName':'EuroStoxx 50'},
	{'Market':'FSMI','ShortName':'FSMI'},
	{'Market':'FTSE','ShortName':'FTSE 100'},
	{'Market':'GASOIL','ShortName':'Gasoil'},
	{'Market':'RBOB','ShortName':'Gasoline (RBOB)'},
	{'Market':'FGBPUSD','ShortName':'GBP/USD (CME)'},
	{'Market':'GOLD','ShortName':'Gold'},
	{'Market':'HS','ShortName':'Hang Seng'},
	{'Market':'CHINA','ShortName':'Hang Seng China'},
	{'Market':'HOIL','ShortName':'Heating Oil'},
	{'Market':'JB','ShortName':'JPN-Bond 10Y'},
	{'Market':'FJPYUSD','ShortName':'JPY/USD (CME)'},
	{'Market':'KS','ShortName':'KOSPI 200'},
	{'Market':'LEAD','ShortName':'Lead'},
	{'Market':'HOGS','ShortName':'Lean Hogs'},
	{'Market':'CATTLE','ShortName':'Live Cattle'},
	{'Market':'LG','ShortName':'Long Gilt'},
	{'Market':'SSG','ShortName':'MSCI Singapore'},
	{'Market':'TW','ShortName':'MSCI Taiwan'},
	{'Market':'FNASDAQ','ShortName':'Nasdaq'},
	{'Market':'NGAS','ShortName':'Natural Gas'},
	{'Market':'NIKOS','ShortName':'Nikkei 225 OSE'},
	{'Market':'FNZDUSD','ShortName':'NZD/USD (CME)'},
	{'Market':'OMXS30','ShortName':'OMX 30'},
	{'Market':'OJ','ShortName':'Orange Juice'},
	{'Market':'JPL','ShortName':'Platinum'},
	{'Market':'RS2000','ShortName':'RS2000'},
	{'Market':'JRU','ShortName':'Rubber'},
	{'Market':'SP500','ShortName':'S&P 500'},
	{'Market':'CAD60','ShortName':'S&P Canada 60'},
	{'Market':'SP400','ShortName':'S&P Midcap'},
	{'Market':'FGBS','ShortName':'Schatz'},
	{'Market':'SILVER','ShortName':'Silver'},
	{'Market':'SOY','ShortName':'Soy'},
	{'Market':'SPI','ShortName':'SPI'},
	{'Market':'SUGAR','ShortName':'Sugar'},
	{'Market':'TN30','ShortName':'T-Bond 30'},
	{'Market':'TN10','ShortName':'T-Note 10'},
	{'Market':'TN5','ShortName':'T-Note 5'},
	{'Market':'TN2','ShortName':'T-Notes 2'},
	{'Market':'TOPIX','ShortName':'Topix'},
	{'Market':'VIX','ShortName':'VIX Future'},
	{'Market':'WHEAT','ShortName':'Wheat'},
	{'Market':'WTICME','ShortName':'WTI (CME)'},
	{'Market':'WTI','ShortName':'WTI Oil'},
	{'Market':'ZINC','ShortName':'Zinc'},
	{'Market':'','ShortName':''}];
